import { VertImageCard } from './types/types';
import { 
    appleRed, 
    appleBlue, 
    appleGreen, 
    vertImages, 
    applePurple, 
    appleYellow, 
    appleGreenMint, 
    appleGreenShade, 
    defaultDarkTabBorderColor, 
} from '@/components/theme/Themed';

export const defaultVertImageCards: VertImageCard[] = [
    new VertImageCard({
        id: 1,
        key: 1,
        name: `Jelly Fish`,
        fontColor: `white`,
        backgroundColor: appleGreen,
        image: vertImages.jelly_fish,
        listID: `1-listColumn-items`,
        summary: `Discover the mesmerizing beauty of jellyfish as they drift gracefully in the ocean.`,
        description: `Discover the mesmerizing beauty of jellyfish as they drift gracefully in the ocean. This card celebrates the tranquility and elegance of marine life.`,
    }),
    new VertImageCard({
        id: 2,
        key: 2,
        name: `Mother Nature`,
        backgroundColor: appleBlue,
        image: vertImages.hand_leaf,
        listID: `1-listColumn-items`,
        summary: `Immerse yourself in the nurturing embrace of nature.`,
        description: `Immerse yourself in the nurturing embrace of nature. This card reflects the harmony between humanity and the environment, symbolized by a delicate hand cradling a leaf. Immerse yourself in the nurturing embrace of nature. This card reflects the harmony between humanity and the environment, symbolized by a delicate hand cradling a leaf. Immerse yourself in the nurturing embrace of nature. This card reflects the harmony between humanity and the environment, symbolized by a delicate hand cradling a leaf. Immerse yourself in the nurturing embrace of nature. This card reflects the harmony between humanity and the environment, symbolized by a delicate hand cradling a leaf. Immerse yourself in the nurturing embrace of nature. This card reflects the harmony between humanity and the environment, symbolized by a delicate hand cradling a leaf. This card reflects the harmony between humanity and the environment, symbolized by a delicate hand cradling a leaf.`,
    }),
    new VertImageCard({
        id: 3,
        key: 3,
        name: `Playing Music`,
        backgroundColor: appleRed,
        listID: `2-listColumn-active`,
        image: vertImages.playing_keyboard,
        summary: `Let the melody flow with the joy of playing music.`,
        description: `Let the melody flow with the joy of playing music. This card represents creativity and the universal language of music that brings people together.`,
    }),
    new VertImageCard({
        id: 4,
        key: 4,
        name: `Festivals`,
        image: vertImages.wind_flag,
        backgroundColor: appleYellow,
        listID: `2-listColumn-active`,
        fontColor: defaultDarkTabBorderColor,
        summary: `Capture the spirit of celebration and unity in vibrant festivals.`,
        description: `Capture the spirit of celebration and unity in vibrant festivals. This card showcases the joy and cultural richness of festive occasions.`,
    }),
    new VertImageCard({
        id: 5,
        key: 5,
        name: `Clean Energy`,
        image: vertImages.wind_mills,
        backgroundColor: applePurple,
        listID: `3-listColumn-complete`,
        summary: `Step into a sustainable future with clean energy.`,
        description: `Step into a sustainable future with clean energy. This card highlights the beauty and importance of renewable energy sources like wind power.`,
    }),
    new VertImageCard({
        id: 6,
        key: 6,
        name: `Singing`,
        listID: `3-listColumn-complete`,
        backgroundColor: appleGreenShade,
        image: vertImages.singing_rockstar,
        summary: `Celebrate the power of vocal expression and the passion of singing.`,
        description: `Celebrate the power of vocal expression and the passion of singing. This card is a tribute to artists and performers who inspire through music.`,
    }),
    new VertImageCard({
        id: 7,
        key: 7,
        name: `The Outside`,
        listID: `3-listColumn-complete`,
        backgroundColor: appleGreenMint,
        image: vertImages.wind_curtains,
        fontColor: defaultDarkTabBorderColor,
        summary: `Feel the refreshing breeze and freedom of the outdoors.`,
        description: `Feel the refreshing breeze and freedom of the outdoors. This card evokes a sense of openness and connection with nature's boundless beauty.`,
    }),
];